# Documentation link:
# https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: frozar/mikado-graph-ci:latest
      user: circleci
  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m

jobs:
  compile-and-test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "shadow-cljs.edn" }}
            - v3-dependencies-

      - run:
          name: install dependencies, compile test
          command: |
            npm i
            shadow-cljs compile ci

      - save_cache:
          paths:
            - ~/.m2
            - node_modules
          key: v3-dependencies-{{ checksum "shadow-cljs.edn" }}

      - run:
          name: Run test
          command: karma start --single-run

  publish-gh-pages:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: git settings, set knwon_hosts, disable jekyll
          command: |
            touch public/.nojekyll
            git config user.email "ci-build@bot.com"
            git config user.name "ci-build"
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "73:c4:05:07:52:04:27:4a:ab:3e:d2:62:7f:e7:e4:7c"

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "shadow-cljs.edn" }}
            - v3-dependencies-

      - run:
          name: Compilation and publish the 'gh-pages' branch
          command: |
            shadow-cljs release app
            npx gh-pages --dotfiles -f -m "[skip ci]" --dist public/

workflows:
 version: 2
 Test_Workflow:
   jobs:
     - compile-and-test
     - publish-gh-pages:
         filters:
           branches:
             only:
               - master
         requires:
           - compile-and-test
